[package]
name = "d0bby"
version = "0.1.0"
authors = ["Marcel Kummer <tanuva@posteo.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.1"
json = "0.12.4"
log = "0.4.17"
paho-mqtt = "0.11.1"
